version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.1
    container_name: kibana-local
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_REQUESTTIMEOUT: 120000
    ports:
      - 5601:5601
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  esdata1:
    driver: local
